# 解答例：Week2 授業前課題3 行列積のスクラッチ

**テキストの目的**
- 数式演算ライブラリのNumPyに慣れる
- 行列演算に慣れる

**どのように学ぶか**
- 行列積の計算を手計算で行った後、スクラッチ実装することで理解を深めていきます。

## 行列積

以下のような行列A、Bを考えます。

$$
A = \left[
\begin{array}{ccc}
  -1 & 2 & 3 \\
  4 & -5 & 6 \\
  7 & 8 & -9
\end{array}
\right],
B = \left[
\begin{array}{ccc}
  0 & 2 & 1 \\
  0 & 2 & -8 \\
  2 & 9 & -1
\end{array}
\right]
$$



NumPyで表すと次のようになります。

In [2]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

## 【問題1】行列積を手計算する

AとBの行列積を手計算で解いてください。

計算過程もマークダウンテキストを用いて説明してください。


$$
AB = 
\left[
\begin{array}{ccc}
  (-1)\times0+2\times0+3\times2 & (-1)\times2+2\times2+3\times9 & (-1)\times1+2\times(-8)+3\times(-1) \\
  4\times0+(-5)\times0+6\times2 & 4\times2+(-5)\times2+6\times9 & 4\times1+(-5)\times(-8)+6\times(-1) \\
  7\times0+8\times0+(-9)\times2 & -7\times0+8\times2+(-9)\times9 & 7\times1+8\times(-8)+(-9)\times(-1)
\end{array}
\right]
=\left[
\begin{array}{ccc}
  6 & 29 & -20 \\
  12 & 52 & 38 \\
  -18 & -51 & -48
\end{array}
\right]
$$

## 【問題2】NumPyの関数による計算

この行列積はNumPyのnp.matmul()やnp.dot()、または@演算子を使うことで簡単に計算できます。

これらを使い行列積を計算してください。

[numpy.matmul — NumPy v1.16 Manual](https://docs.scipy.org/doc/numpy/reference/generated/numpy.matmul.html#numpy.matmul)

[numpy.dot — NumPy v1.16 Manual](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html)

《3種類の違い》

np.matmul()とnp.dot()は3次元以上の配列で挙動が変わります。@演算子はnp.matmul()と同じ働きをします。

今回のような2次元配列の行列積ではnp.matmul()や@演算子が公式に推奨されています。以下はnp.dot()の説明からの引用です。

If both a and b are 2-D arrays, it is matrix multiplication, but using matmul or a @ b is preferred.

In [6]:
c_ndarray = a_ndarray@b_ndarray
print(c_ndarray)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


# 3.行列積のスクラッチ実装

np.matmul()やnp.dot()、または@演算子を使わずに、手計算で行った計算過程をNumPyによるスクラッチ実装で再現していきましょう。これにより、行列積の計算に対する理解を深めます。ここで考えるのは行列AとBのような次元が2の配列に限定します。

## 【問題3】ある要素の計算を実装

In [7]:
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

matrix_product00 = (a_ndarray[0]*b_ndarray[:, 0]).sum()
print(matrix_product00)

6


## 【問題4】行列積を行う関数の作成

In [28]:
def matrix_product(a, b):
    """
    行列AとBの行列積を行う関数
    
    Parameteres
    --------------
    a, b : ndarray
        行列AとB
    
    Returns
    --------------
    ab : ndarray
        行列AとBの行列積
    """
    ab = np.empty((a.shape[0], b.shape[1]))
    
    for i in  range(a.shape[0]):
        for j in range(b.shape[1]):
            ab[i, j] = (a[i]*b[:, j]).sum()
    return ab

# 行列a_ndarrayとb_ndarrayを代入し、計算結果を出す
print(matrix_product(a=a_ndarray, b=b_ndarray))

[[  6.  29. -20.]
 [ 12.  52.  38.]
 [-18. -51. -48.]]


# 4.行列積が定義されない組み合わせの行列

## 【問題5】計算が定義されない入力を判定する

In [40]:
def matrix_product_check(a, b):
    ab = np.empty((a.shape[0], b.shape[1]))

    if a.shape[1] == b.shape[0]:
        for i in  range(a.shape[0]):
            for j in range(b.shape[1]):
                ab[i, j] = (a[i]*b[:, j]).sum()
        return ab
    else:
        print("Cannot calculationan(a.shape[1] != b.shape[0]) : {} != {}".format(a.shape[1], b.shape[0]))
        return None
        
d = np.array([[-1, 2, 3], [4, -5, 6]])
e = np.array([[-9, 8, 7], [6, -5, 4]])
print("計算結果: {}".format(matrix_product_check(d, e)))

Cannot calculationan(a.shape[1] != b.shape[0]) : 3 != 2
計算結果: None


## 【問題6】転置
**ポイント：行と列の数を合わせれば計算可能！**


片方の行列を転置することで、行列積が計算できるようになります。

np.transpose()や.T アトリビュートを用いて転置し、行列積を計算してください。

[numpy.transpose — NumPy v1.16 Manual](https://docs.scipy.org/doc/numpy/reference/generated/numpy.transpose.html)

[numpy.ndarray.T — NumPy v1.16 Manual](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.T.html)

In [49]:
d = np.array([[-1, 2, 3], [4, -5, 6]])
e = np.array([[-9, 8, 7], [6, -5, 4]])

d_t = d.transpose() #dを転置
print("dを転置した計算結果：\n{}".format(d_t@e))

e_t = e.transpose() #eを転置
print("eを転置した計算結果：\n{}".format(d@e_t))

dを転置した計算結果：
[[ 33 -28   9]
 [-48  41  -6]
 [  9  -6  45]]
eを転置した計算結果：
[[ 46  -4]
 [-34  73]]
